export const projects = [
  {
    title: 'AceHaematology',
    description:
      'A comprehensive FRCPath haematology exam preparation platform with 1000+ practice questions, mock exams, and expert-crafted content designed by UK haematologists.',
    image: '/images/project-acehaematology.svg',
    tags: ['Next.js', 'TypeScript', 'Medical Education', 'Exam Preparation', 'React'],
    demoUrl: 'https://www.acehaematology.com/',
    githubUrl: 'https://github.com/jaskaranpr/acehaematology',
    category: 'Web App',
    featured: true,
  },
  {
    title: 'HRSolx',
    description:
      'Smart hiring platform connecting HR professionals with verified skilled workers across manufacturing, automotive, construction, and logistics industries with AI-powered matching.',
    image: '/images/project-hrsolx.svg',
    tags: ['Next.js', 'TypeScript', 'AI/ML', 'HR Tech', 'Recruitment', 'React'],
    demoUrl: 'https://www.hrsolx.com/',
    githubUrl: 'https://github.com/jaskaranpr/hrsolx',
    category: 'Web App',
    featured: true,
  },
  {
    title: 'HRSolx Mobile App',
    description:
      'Mobile application for skilled workers to create profiles, manage availability, and connect with employers through secure Aadhaar verification and real-time job matching.',
    image: '/images/project-hrsolx-mobile.svg',
    tags: ['React Native', 'TypeScript', 'Mobile App', 'HR Tech', 'Authentication', 'Real-time'],
    demoUrl: 'https://play.google.com/store/apps/details?id=com.hrsolx.worker',
    githubUrl: 'https://github.com/jaskaranpr/hrsolx-mobile',
    category: 'Mobile App',
    featured: true,
  },
  {
    title: 'E-commerce Platform',
    description: 'A full-featured e-commerce platform built with Next.js and Stripe integration.',
    image: '/projects/ecommerce.jpg',
    tags: ['Next.js', 'TypeScript', 'Stripe', 'TailwindCSS'],
    demoUrl: 'https://demo-ecommerce.jaskaran.in',
    githubUrl: 'https://github.com/jaskaranpr/ecommerce',
    category: 'Web App',
    featured: true,
  },
  {
    title: 'Portfolio Website',
    description: 'A modern portfolio website built with Next.js and TailwindCSS.',
    image: '/projects/portfolio.jpg',
    tags: ['Next.js', 'TailwindCSS', 'Framer Motion'],
    demoUrl: 'https://jaskaran.in',
    githubUrl: 'https://github.com/jaskaranpr/portfolio',
    category: 'Web App',
    featured: true,
  },
  {
    title: 'Task Management App',
    description: 'A task management application with real-time updates and collaboration features.',
    image: '/projects/task-manager.jpg',
    tags: ['React', 'Firebase', 'Material-UI'],
    demoUrl: 'https://task-manager.jaskaran.in',
    githubUrl: 'https://github.com/jaskaranpr/task-manager',
    category: 'Web App',
    featured: false,
  },
  {
    title: 'Weather Dashboard',
    description:
      'A weather dashboard that shows current weather and forecasts for multiple cities.',
    image: '/projects/weather.jpg',
    tags: ['React', 'OpenWeather API', 'ChartJS'],
    demoUrl: 'https://weather.jaskaran.in',
    githubUrl: 'https://github.com/jaskaranpr/weather-dashboard',
    category: 'Web App',
    featured: false,
  },
  {
    title: 'Blog Platform',
    description: 'A blog platform with markdown support and user authentication.',
    image: '/projects/blog.jpg',
    tags: ['Next.js', 'MDX', 'Auth.js'],
    demoUrl: 'https://blog.jaskaran.in',
    githubUrl: 'https://github.com/jaskaranpr/blog',
    category: 'Web App',
    featured: true,
  },
  {
    title: 'Recipe Finder',
    description: 'A recipe finder application with search and filtering capabilities.',
    image: '/projects/recipe.jpg',
    tags: ['React', 'API Integration', 'Styled Components'],
    demoUrl: 'https://recipe.jaskaran.in',
    githubUrl: 'https://github.com/jaskaranpr/recipe-finder',
    category: 'Web App',
    featured: false,
  },
];
